# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo HTML5 UP Alpha"
license = "Creative Commons"
licenselink = "https://github.com/dewittn/hugo-html5up-alpha/blob/master/LICENSE"
description = "A Hugo port of the static html template Alpha by HTML5 UP."
homepage = "https://github.com/dewittn/hugo-html5up-alpha"
tags = ["blog", "html5up","responsive","business"]
features = ["blog","page bundle","forms"]
min_version = "0.70.0"
demosite = "https://hugo-html5up-alpha.nelsonroberto.com"

[author]
  name = "Nelson/Roberto"
  homepage = "https://nelsonroberto.com/"

# If porting an existing theme
[original]
  name = "@ajlkn"
  homepage = "https://html5up.net"
  repo = ""