## Everything below is specific to the hugoBasicExample
baseURL = "https://hugo-html5up-alpha.nelsonroberto.com/"

[params]
  description = "A Hugo port of the static html template Alpha by HTML5 UP."
  mainSections = ["post"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true