## Config for extra markdown features
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    [goldmark.parser.attribute]
      block = true
      title = true
      table = true
  [goldmark.renderer]
    unsafe = true
[highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "bw"
  tabWidth = 4